 bind_to_address "127.0.0.1"
  music_directory "/Users/sarvagya_sharma/songs"
  playlist_directory "/Users/sarvagya_sharma/songs/playlists"
  db_file      "/Users/sarvagya_sharma/.mpd/mpd.db"
  log_file      "/Users/sarvagya_sharma/.mpd/mpd.log"
  pid_file      "/Users/sarvagya_sharma/.mpd/mpd.pid"
  state_file     "/Users/sarvagya_sharma/.mpd/mpdstate"

audio_output {
     type  "osx"
     name  "My Mac Device"
     mixer_type      "software"
 }


audio_output {
    type "fifo"
    name "viz"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
    buffer_time "100000"
}
