set -g default-terminal "screen-256color"
set -g mouse on
setw -g mode-keys vi

# copy mode keybindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# window and pane numbering 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# prefix key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# bindings
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config Reloaded"

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"

unbind %
bind | split-window -h -c "#{pane_current_path}"

# Easy resizing (does not conflict with vim-tmux-navigator)
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

# Maximize the current pane
bind -r m resize-pane -Z

# window reordering in current session
bind-key -n C-M-Left swap-window -t -1\; select-window -t -1
bind-key -n C-M-Right swap-window -t +1\; select-window -t +1

# Set this variable to use later
set -g @USER "#(whoami)"

# CUSTOM THEME
# Styles
set -g @blue "#65D1FF"
set -g @green "#3EFFDC"
set -g @violet "#FF61EF"
set -g @yellow "#FFDA7B"
set -g @red "#FF4A4A"
set -g @fg "#c3ccdc"
set -g @bg "#112638"
set -g @inactive_bg "#2c3043"
set -g @gray_light "#D8DEE9"
set -g @gray_medium "#ABB2BF"
set -g @gray_dark "#3B4252"
set -g @blue_muted "#81A1C1"
set -g @bg_dark "#011423"
set -g @bg_dark_new "#011628"
set -g @bg_highlight "#143652"
set -g @bg_search "#0A64AC"

set -g status-position bottom
set -g status-style "fg=#{@gray_light},bg=#{@bg_dark_new}"


# LEFT STATUS BAR
set -g status-left-length 100
# taken from: https://github.com/catppuccin/tmux/discussions/317#discussioncomment-11064512
# Can also use this for client_prefix visibility #{?client_prefix,#[fg=${bg}#,bold#,bg=${green}]  #S,#[fg=${green}#,bold#,bg=default]  #S} \
set -g status-left "\
#{?client_prefix,#[fg=#{@violet}#,bold#,bg=default]  #S,#[fg=#{@blue}#,bold#,bg=default]  #S} \
#[fg=#{@inactive_bg},bg=default]|\
#[fg=#{@blue},bold,bg=default]   #{pane_current_command} \
#[fg=#{@inactive_bg},bg=default]|\
#[fg=#{@blue},bold,bg=default]   #{=/-32/...:#{s|#{@USER}|~|:#{b:pane_current_path}}} \
"

# RIGHT STATUS BAR
# set -g status-right '#(TZ="Asia/Kolkata" date +"%%h %%d %%Y %%I:%%M:%%S %p")'
set -g status-right-length 100
set -g status-right "\
  #(TZ='Asia/Kolkata' date +'%%Y-%%m-%%d %%I:%%M %p') \
"

set -g status-interval 5
set -g window-status-current-format "#[fg=#{@blue},bold] #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g status-justify absolute-centre
set -g message-style "fg=#{@blue},bg=#{@bg_dark_new}"
set -g mode-style "fg=#{@gray_dark},bg=#{@blue_muted}"
set -g pane-border-style "fg=#{@gray_dark}"
set -g pane-active-border-style "fg=#{@gray_medium}"


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'

# Initialize TPM (Keep this at the bottom)
run '~/.tmux/plugins/tpm/tpm'
