# set -g default-terminal "screen-256color"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g mouse on
setw -g mode-keys vi

set -sg escape-time 0

# copy mode keybindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# window and pane numbering 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# prefix key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# bindings
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config Reloaded"

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"

unbind %
bind | split-window -h -c "#{pane_current_path}"

# Easy resizing (does not conflict with vim-tmux-navigator)
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

# Maximize the current pane
bind -r m resize-pane -Z

# CUSTOM THEME
# Styles
blue="#65D1FF"
green="#3EFFDC"
violet="#FF61EF"
yellow="#FFDA7B"
red="#FF4A4A"
fg="#c3ccdc"
bg="#112638"
inactive_bg="#2c3043"
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
blue_muted="#81A1C1"
bg_dark="#011423"
bg_dark_new="#011628"
bg_highlight="#143652"
bg_search="#0A64AC"

set -g status-position bottom
set -g status-left-length 100
set -g status-style "fg=${gray_light},bg=#011628"
set -g status-left "#[fg=${green},bold]#S"
set -g status-right '#(TZ="Asia/Kolkata" date +"%%h %%d %%Y %%I:%%M:%%S %%p")'
set -g status-interval 1
set -g window-status-current-format "#[fg=${blue},bold] #[underscore]#I:#W"
set -g window-status-format " #I:#W"
set -g status-justify centre
set -g message-style "fg=${blue},bg=${bg_dark_new}"
set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrent-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TPM (Keep this at the bottom)
run '~/.tmux/plugins/tpm/tpm'
